config/routes.rb
Rails.application.routes.draw do
  resources :films
  root to: 'films#index'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
    # index
    def index
     @films = Film.all
   end
   
   # new
   def new
     @film = Film.new
   end
   
    # create
    def create
        @film = Film.create!(film_params)
        redirect_to film_path(@film)
    end
   
   #show
   def show
     @film = Film.find(params[:id])
   end
   
   # edit
   def edit
     @film = Film.find(params[:id])
   end
   
   
   # update
   def update
     @film = Film.find(params[:id])
     @film.update(film_params)
   
    redirect_to film_path(@film)
   end
   
   # destroy
   def destroy
     @film = Film.find(params[:id])
     @film.destroy
   
    redirect_to films_path
   end
   
   private
   def film_params
     params.require(:film).permit(:title, :genre, :year, :synopsis, :picture)
     end
   end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/edit.html.erb
<h2>Edit Film</h2>

<%= render "partials/film_form"%>

<form action="/films/<%= @film.id %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input class="delete" type="submit" value="Delete Song">
</form>

app/views/films/index.html.erb
<h2>Films <a href="/films/new">(+)</a></h2>

<ul>
  <% @films.each do |film| %>
    <li>
    <%= link_to film.title, film_path(film) %>
    </li>
  <% end %>
</ul>

app/views/films/new.html.erb
<h1>New Film</h1>
<%= render "partials/film_form"%>

app/views/films/show.html.erb
<h1><%= @film.title %></h1>
<%= link_to  "home", films_path %>
<br />
<br />

<%= image_tag @film.picture %>
<br />
<br />
<p>genre: <%= @film.genre %></p>
<p>year: <%= @film.year %></p>
<p>synopsis: <%= @film.synopsis %></p>

<div>
<br />
<br />
<br />

<%= link_to  'Edit', edit_film_path %>
<%= form_for @film, method: :delete do |f| %>
    <%= f.submit'Delete', class: 'delete' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>